apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
  - name: api
    port: {{ .Values.api.ports.servicePort }}
    targetPort: {{ .Values.api.ports.containerPort }}
  selector:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
---
