variable "bastion_subnet" {}
variable "vpc_id" {}
variable "public_key" {}
variable "bastion_private_ip" {}
variable "vpn_endpoint" {}
variable "vpn_route" {}
variable "bastion_instance_type" {}
variable "project_name" {}
variable "common_tags" {}