apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: testapp-secrets
  namespace: testapp-web
spec:
  backendType: secretsManager
  region: us-east-1
  dataFrom:
  - testapp/secrets
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: testapp-secrets
  namespace: testapp-api
spec:
  backendType: secretsManager
  region: us-east-1
  dataFrom:
  - testapp/secrets  