apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  host: {{ .Values.web.name }}.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN    
  subsets:
  - name: {{ .Release.Namespace }}
    labels:
      component: primary
    
